-- Supabase Migration File
-- Generated for CRM Integration

-- Stages Table
CREATE TABLE IF NOT EXISTS stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  "order" INTEGER NOT NULL
);

-- Import Batches Table
CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename TEXT,
  lead_count INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Leads Table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT,
  email TEXT,
  phone TEXT,
  website TEXT,
  segment TEXT,
  location TEXT,
  size TEXT,
  cnpj TEXT,
  stage_id BIGINT REFERENCES stages(id),
  priority TEXT DEFAULT 'Medium',
  value REAL DEFAULT 0,
  batch_id BIGINT REFERENCES import_batches(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_interaction TIMESTAMPTZ
);

-- Interactions Table
CREATE TABLE IF NOT EXISTS interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  type TEXT, -- 'call', 'email', 'whatsapp', 'meeting', 'note'
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  title TEXT,
  due_date TIMESTAMPTZ,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Saved Reports Table
CREATE TABLE IF NOT EXISTS saved_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  config JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Quick Commands Table
CREATE TABLE IF NOT EXISTS quick_commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command TEXT NOT NULL,
  result TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Settings Table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Users Table (Note: Supabase has its own auth.users table, but we can have a public.users profile table)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'user'
);

-- Enable Row Level Security (RLS)
ALTER TABLE stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Create policies (Simplistic for now: allow all for authenticated users)
CREATE POLICY "Allow all for authenticated users" ON stages FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON leads FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON interactions FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON tasks FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON import_batches FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON saved_reports FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON quick_commands FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON settings FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all for authenticated users" ON profiles FOR ALL TO authenticated USING (true);

-- Seed initial stages
INSERT INTO stages (name, color, "order") VALUES 
('Lead', '#94a3b8', 1),
('1° mensagem', '#60a5fa', 2),
('1° ligação', '#3b82f6', 3),
('2° mensagem', '#818cf8', 4),
('2° ligação', '#6366f1', 5),
('Material preparatório D.I', '#a855f7', 6),
('Diagnóstico', '#ec4899', 7),
('Proposta', '#fbbf24', 8),
('Follow up', '#f97316', 9),
('Fechamento', '#10b981', 10),
('Indicação', '#06b6d4', 11)
ON CONFLICT DO NOTHING;

-- Seed default settings
INSERT INTO settings (key, value) VALUES 
('company_name', 'Minha Empresa CRM'),
('currency', 'BRL')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
